### ISSUE TITLE
El cron sobreescribe los precios en las ordenes

### ISSUE THREAD

**Issue by zubeldialuis** [dondominio/whmcs-addon#2]
Si configuro un precio especifico en un dominio para la renovación posterior, el cron "machaca" este precio. 

Tine sentido que si un precio de la renovación un dominio cambia, las ordenes actualicen su precio, pero debería haber algun modo para los que fueron modificados manualmente no sean sobrescritos.

**Comment by MikyKuroneko** [comment]
La configuración de TLDs permite configurar el cron para ignorar ciertas extensiones de dominio. Por favor, consulte el apartado correspondiente del manual en la dirección https://dev.dondominio.com/whmcs/docs/addon/#cambio-manual-de-precios.
