### ISSUE TITLE
No sale de la pantalla donde lista todos los TLD

### ISSUE THREAD

**Issue by ysilvela** [dondominio/whmcs-addon#3]
En la administración, Modelos->Don dominio manager, no consigo salir de la ventana donde lista los dominios para actualizar los precios. 

Ya no me sale el menu de pestañas donde por ejemplo se cambia el usuario de la API.

**Comment by MikyKuroneko** [comment]
Hola @ysilvela, ¿podrías indicarnos qué versión de WHMCS estás usando, y si estás usando algún tipo de tema personalizado para el panel de administración?

Las opciones de menú que comentas se encuentran, normalmente, en el menú izquierdo del panel de WHMCS. Comprueba que no lo tienes minimizado tampoco (aparecería, en este caso, un botón de "Open sidebar" a la izquierda).

Te adjunto una captura donde puedes observar dónde se encuentra este menú (hecha en WHMCS 7.4.1).

![screenshot-2018-01-10-163730](https://user-images.githubusercontent.com/3064045/34780920-bbd52a22-f624-11e7-8f45-099f41154e0e.png)
