### ISSUE TITLE
No se añaden TLDs disponibles a WHMCS

### ISSUE THREAD

**Issue by ysilvela** [dondominio/whmcs-addon#4]
Cuando desde la ventana de "TLDs disponibles" añado un nuevo TLD a mi WHMCS, no se termina añadiendo a pesar de que sale un mensaje en verde que dice que lo ha añadido. Voy a la ventana de actualizar tarifas y no se encuentra.

Gracias.

**Comment by MikyKuroneko** [comment]
Hola,
Hemos actualizado la versión del plugin para añadir compatibilidad con la última versión de WHMCS. Por favor, instale esta última versión (disponible en https://github.com/dondominio/whmcs-addon/releases/tag/v1.9.3) y si sigue teniendo problemas abra un ticket con soporte.

Gracias.
